meat_dish(beef).
meat_dish(turkey).
meat_dish(lamb).
meat_dish(goat).
fish_dish(crab).
fish_dish(salmon).
fish_dish(tuna).
vegetarian_dish(pasta).
vegetarian_dish(black_beans).
vegetarian_dish(chickpeas).
vegetarian_dish(spinach).
